### ISSUE TITLE
Alignment is not accounted for

### ISSUE THREAD

**Issue by BurntSushi** [nabijaczleweli/safe-transmute-rs#22]
As far as I can tell, alignment isn't accounted for at all in this crate. You seem to assert that converting a `*const u8` to a `*const T` is OK even when `T` has an alignment greater than `1`. For example, your [`guarded_transmute`](https://github.com/nabijaczleweli/safe-transmute-rs/blob/456c9857a6e753ab8a55e9ad669d2b312819103b/src/lib.rs#L129) function checks the sizes, but not alignment, and then proceeds to dereference a `*const T` pointer even though it might have an alignment greater than `1`. That's UB. This is then used as an implementation of functions like [`guarded_transmute_pod`](https://github.com/nabijaczleweli/safe-transmute-rs/blob/456c9857a6e753ab8a55e9ad669d2b312819103b/src/pod.rs#L64-L66) to declare that it is safe, but it is in fact not safe.

**Comment by BurntSushi** [comment]
It may be possible salvage the safety guarantees you want to provide by using explicit unaligned loads: https://doc.rust-lang.org/std/ptr/fn.read_unaligned.html

**Comment by Enet4** [comment]
@BurntSushi Thanks for the finding. Admittedly, this crate tends to sail through some murky laundry-eating waters.

I recall that a previous version of the crate would perform the check with `align_of` instead of `size_of`, but eventually we realized that this wouldn't work for compound structs. Even so, this wasn't an actual alignment check of the byte slice, but a check for the target type's alignment with the length of the slice. Would it become safe if we ensure that the address pointed by the slice is a multiple of the target type's alignment? 

I made a few tests that would read unaligned slices in #21. They all seem to pass, but I understand that this doesn't prove memory safety (good behaviour in UB is still possible...).

**Comment by BurntSushi** [comment]
> Would it become safe if we ensure that the address pointed by the slice is a multiple of the target type's alignment?

This seems plausible, yes.

Note that I am not an expert in Rust's UB. Honestly, probably very few people are, because we don't have a formal semantics for it yet. I would strongly urge you to put a warning somewhere around this crate that it hasn't been thoroughly vetted, but that such vetting would be welcome. :-)

In general, I like the ideas motivating this crate, but I think we need to be super careful about what we're claiming is safe and what isn't.

**Comment by BurntSushi** [comment]
> I made a few tests that would read unaligned slices in #21. They all seem to pass, but I understand that this doesn't prove memory safety (good behaviour in UB is still possible...).

Emphatically, yes. And it may vary by platform.

**Comment by Enet4** [comment]
> Note that I am not an expert in Rust's UB. Honestly, probably very few people are, because we don't have a formal semantics for it yet. I would strongly urge you to put a warning somewhere around this crate that it hasn't been thoroughly vetted, but that such vetting would be welcome. :-)

Indeed. @nabijaczleweli can you work on this?

> In general, I like the ideas motivating this crate, but I think we need to be super careful about what we're claiming is safe and what isn't.

I agree. This crate emerged with some exciting use cases, but once the first versions were laid out, we did realize that making it safe was not very trivial. The feedback from better informed members of the community has been invaluable so far, and I hope to ensure that this never hits 1.0.0 until we're sure that the non-`unsafe` API is really safe.

**Comment by nabijaczleweli** [comment]
> this wouldn't work for compound structs

Was `#[repr(C)]` structs, actually.

> put a warning somewhere

Cool and good. (Timing: post-PRs and pre-release.)

> ensure that this never hits 1.0.0 until we're sure that the non-unsafe API is really safe

Well, since we've merged some magenta changes into `master`, which are doomed to release, we've to bump major (semver is cool and good). And, since major is `0`, it will be `1`. Frankly, I don't see people's obsession with `v1.0.0` meaning something in semver-enforced environments.

**Comment by Enet4** [comment]
> Well, since we've merged some magenta changes into master, which are doomed to release, we've to bump major (semver is cool and good). And, since major is 0, it will be 1.

That's not quite how semver works though. 0-major versions are pre-releases, so breaking changes are [always permitted](https://semver.org/#spec-item-4).

**Comment by Enet4** [comment]
On phone right now, so I'll be brief:

1. [C-STABLE](https://rust-lang-nursery.github.io/api-guidelines/necessities.html#public-dependencies-of-a-stable-crate-are-stable-c-stable).
2. Two wrongs don't make a right.
3. It was a mistake that had to be addressed. It's not like people had the crate automatically updated to a breaking version. Besides, that was increasingly bad because it made us realize that we were far from attaining the feature that the crate was originally designed for: safe transmutation. We should strive towards no UB through our safe functions, and until then we ought to stick to pre-releases.

**Comment by nabijaczleweli** [comment]
Released in [`v0.9.0`](https://github.com/nabijaczleweli/safe-transmute-rs/releases/tag/v0.9.0).
