### ISSUE TITLE
PodTransmutable on tuples

### ISSUE THREAD

**Issue by nilgoyette** [nabijaczleweli/safe-transmute-rs#29]
I'm playing with a RGB image reader and writer for `nifti-rs`. As you probably know, each pixel is defined as a `(u8, u8, u8)`, so I tried adding

    unsafe impl PodTransmutable for (u8, u8, u8) {}

believing that it works like `Send` and `Sync`, but I can't `impl doesn't use types inside crate`. What's the trick? Is it possible to transmute a `&[(u8, u8, u8)]` to their bytes?

**Comment by Enet4** [comment]
That error seems to come from the fact that you cannot implement a foreign trait `PodTransmutable` for types which you did not make. We would either have to add this implementation to this crate, or you would have to make a newtype around the tuple and `impl` the trait for that one.

However, I am not sure whether it is safe to assume memory transparency from a tuple. I believe that the compiler provides no guarantees regarding how each element in a plain tuple is positioned/aligned in memory, making it even less useful.

However, `[u8; 3]` would certainly bring better guarantees in this case, and it seems to be a feasible replacement for your use case, since each component is a `u8`. Let me try to add some implementations for fixed size arrays.

**Comment by nilgoyette** [comment]
Oh, so you would define a RGB pixel as `[u8; 3]` instead of `(u8, u8, u8)`? Hum, I guess it's as good. I don't think the nifti standard allows mixed types anyway. RGB[A] and COMPLEX### should work.

I just had the reflex to use a tuple because it "looks good" and that's what NiBabel does.

**Comment by Enet4** [comment]
> I just had the reflex to use a tuple because it "looks good" and that's what NiBabel does.

I understand the sentiment, but Python is a whole different place as well, especially when it comes to the type system. :) We have fixed size arrays here, and we can even pattern match on them.

**Comment by nabijaczleweli** [comment]
Released in [`v0.9.0`](https://github.com/nabijaczleweli/safe-transmute-rs/releases/tag/v0.9.0).
