### ISSUE TITLE
Non-unsafe functions for PODs?

### ISSUE THREAD

**Issue by nabijaczleweli** [nabijaczleweli/safe-transmute-rs#5]
Since PODs (and only PODs) are actually safe to type-pun we could probably totally do that!

Now if only there was a [`std::is_pod<T>`](http://en.cppreference.com/w/cpp/types/is_pod) in Rust…

**Comment by nabijaczleweli** [comment]
Turns out [not even PODs are safe](https://chat.stackoverflow.com/transcript/62927?m=39499021#39499021)! Great!

**Comment by Enet4** [comment]
[Better permalink](https://chat.stackoverflow.com/transcript/message/39498626#39498626).

I suggest that we attempt to grab as many situations of safe transmutation as possible in a case-by-case basis. In particular:

- integer type (`u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64`, `u128`, `i128`), `bool`, `char`, or float types (`f32`, `f64`) to another integer type is safe because all possible bit states are valid states;
- the same to `f32` or `f64` [is also safe if we assume that transmuting to signalling NaNs are a no-problem](https://stackoverflow.com/a/43814803/1233251). This isn't 100% agreed upon, though, because certain changes in LLVM implementation details could influence this safety (see [rust/#39271](https://github.com/rust-lang/rust/pull/39271). On the safe side, we could probably have a function that guards, transmutes and then masks the signalling bits.
- To `bool`, we could first transmute to `u8`, check whether each byte is either 0 or 1, and raise an error otherwise.

It's likely that we'll need separate functions for each case.

**Comment by nabijaczleweli** [comment]
Released in [v0.5.0](https://github.com/nabijaczleweli/safe-transmute-rs/releases/tag/v0.5.0).
